Legg til nynorsk
navikt/familie-ba-soknad pull request #170
Opened 2021-05-18 08:42 UTC by daphneleebeek

### 💰 Hva forsøker du å løse i denne PR'en
Legger til nynorsk

### 🔎️ Er det noe spesielt du ønsker å fremheve?
Nei

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [x] Jeg har testet mine endringer i henhold til akseptansekriteriene/skissene 🕵️
- [ ] Jeg har testet endringene mine i mobilstørrelse, zoom 200%, skalerer riktig med endret tekststørrelse i browser 📱
- [ ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- [ ] Jeg har fikset en bug, og skrevet regresjonstest for denne

_Jeg har ikke skrevet tester fordi:_

### 🤷‍♀ ️Hvor er det lurt å starte?
_F.eks. commit for commit, alt i ett?_
Alt i ett

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [x] Nei
  
### 👀 Screen shots
_Har det visuelle endret seg? Legg til før- og etterbilder!_

2021-05-18 11:50 UTC, norakf approved these changes

2021-05-19 07:12 UTC, bjornsnoen-nav requested changes

2021-05-19 07:12 UTC, bjornsnoen-nav commented on src/frontend/index.tsx
> +        <SprakProvider tekster={{ nb: bokmål, nn: nynorsk }} defaultLocale={LocaleType.nb}>
Må vel også legge til en import av `i18n-iso-countries/langs/nn.json`  rett over her?

2021-05-19 09:40 UTC, daphneleebeek commented on src/frontend/index.tsx
> +        <SprakProvider tekster={{ nb: bokmål, nn: nynorsk }} defaultLocale={LocaleType.nb}>
Bra catch, fiksa nå :)

2021-05-19 10:11 UTC, bjornsnoen approved these changes

2021-05-19 10:16 UTC, bjornsnoen-nav approved these changes

2021-05-19 11:05 UTC, merged